# Import Liberaries

In [1]:
import json
import re
from sklearn.preprocessing import LabelEncoder
import numpy as np
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

Read Data

In [2]:
with open('data.json') as file:
    data=json.load(file)

In [6]:
data['data'][0]

{'label': 'greeting',
 'patterns': ['Hi', 'Hey', 'Is anyone there?', 'Hello', 'Hay'],
 'responses': ['Hello', 'Hi', 'Hi there', 'Hey']}

Create training example , label and response

In [7]:
training_example=[]
training_labels=[]
response=[]

for example in data['data']:
    for pattern in example['patterns']:
        training_example.append(pattern)
        training_labels.append(example['label'])
    response.append(example['responses'])

In [8]:
print("training example ")
print(training_example)

training example 
['Hi', 'Hey', 'Is anyone there?', 'Hello', 'Hay', 'Who are you?', 'What are you?', 'Who you are?', 'what is your name?', 'what should I call you?', 'whats your name?', 'Could you help me?', 'give me a hand please.', 'Can you help?', 'What can you do for me?', 'I need a support.', 'I need a help', 'support me please', "I'm sad", "I'm so sad", 'I feel bad', 'I am alone', 'I have a lot of problems', 'I am depressed', 'I need encouragement', "I'm so frustrated", "I'm so frustrated with myself because I lost confidence", 'Thanks', 'Thank you', "That's helpful", 'Thanks for the help', 'Bye', 'See you later', 'Goodbye']


In [9]:
print("training label ")
print(training_labels)

training label 
['greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'about', 'about', 'about', 'name', 'name', 'name', 'help', 'help', 'help', 'help', 'help', 'help', 'help', 'sad', 'sad', 'sad', 'sad', 'sad', 'positive_sen', 'positive_sen', 'positive_sen', 'positive_sen', 'thanks', 'thanks', 'thanks', 'thanks', 'goodbye', 'goodbye', 'goodbye']


In [10]:
print('Response')
print(response)

Response
[['Hello', 'Hi', 'Hi there', 'Hey'], ["I'm Zain, your bot assistant", "I'm Zain , an Artificial Intelligent bot", "I'm Zain , an Amit Artificial Intelligent bot"], ['You can call me Zain.', "I'm Zain!", 'Just call me as Zain'], ['Tell me how can assist you', 'Tell me your problem to assist you', 'Yes Sure, How can I support you'], ['It is better for you to pray', 'Get close to Allah', 'You can watch a movie', 'Go out with friends'], ['I think you are great!', 'You are a genius!', 'You are awesome'], ['Happy to help!', 'Any time!', 'My pleasure', "You're most welcome!"], ['See you later', 'Have a nice day', 'Bye! Come back again']]


In [11]:
len(training_labels)

34

In [13]:
set(training_labels)

{'about',
 'goodbye',
 'greeting',
 'help',
 'name',
 'positive_sen',
 'sad',
 'thanks'}

In [ ]:
len(set(training_labels))

8

Preprocessing

In [ ]:
training_example

In [19]:
def clean_text(sentences):
    result=[]
    for sentence in sentences:
        #sentence=re.sub(r'\W',' ',sentence)# pattern  # text
        sentence=sentence.lower()
        result.append(sentence)

    return result

In [20]:
training_example=clean_text(training_example)

convert label values

In [21]:
le=LabelEncoder()
le.fit(training_labels)
training_labels=le.fit_transform(training_labels)

In [22]:
training_labels

array([2, 2, 2, 2, 2, 0, 0, 0, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 6, 6, 6, 6,
       6, 5, 5, 5, 5, 7, 7, 7, 7, 1, 1, 1])

In [23]:
training_labels=to_categorical(training_labels)
training_labels

array([[0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 

Convert words to vectors

In [24]:
from tensorflow.keras.preprocessing.text import one_hot
sequnces=[one_hot(example,50,filters='') for example in training_example]
print(sequnces)

# onvert text into one-hot encoded sequences
# 50 >>>>The vocab_size parameter specifies the size of the vocabulary,
#  and filters='' means that no characters should be filtered during tokenization.

[[17], [29], [17, 14, 11], [47], [42], [16, 26, 44], [43, 26, 44], [16, 13, 14], [43, 17, 40, 39], [43, 24, 37, 49, 44], [2, 40, 39], [33, 13, 9, 23], [44, 38, 25, 22, 29], [46, 13, 21], [43, 46, 13, 35, 47, 23], [37, 33, 25, 27], [37, 33, 25, 9], [25, 38, 11], [14, 15], [14, 9, 15], [37, 34, 9], [37, 46, 4], [37, 32, 25, 14, 34, 45], [37, 46, 11], [37, 33, 14], [14, 9, 1], [14, 9, 1, 27, 36, 27, 37, 29, 14], [12], [15, 13], [5, 35], [12, 47, 37, 9], [19], [18, 13, 22], [17]]


In [25]:
toknizer=Tokenizer(num_words=100)
toknizer.fit_on_texts(training_example)
sequnces=toknizer.texts_to_sequences(training_example)
print(sequnces)

[[23], [24], [11, 25, 26], [27], [28], [12, 8, 1], [3, 8, 1], [12, 1, 8], [3, 11, 13, 14], [3, 29, 2, 30, 1], [31, 13, 14], [32, 1, 4, 5], [33, 5, 6, 34, 15], [16, 1, 4], [3, 16, 1, 35, 17, 5], [2, 9, 6, 18], [2, 9, 6, 4], [18, 5, 15], [7, 19], [7, 10, 19], [2, 36, 37], [2, 20, 38], [2, 39, 6, 40, 41, 42], [2, 20, 43], [2, 9, 44], [7, 10, 21], [7, 10, 21, 45, 46, 47, 2, 48, 49], [22], [50, 1], [51, 52], [22, 17, 53, 4], [54], [55, 1, 56], [57]]


In [26]:
padded_sequence=pad_sequences(sequnces,truncating='post',maxlen=20)
print(padded_sequence)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 23]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 24]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 11 25 26]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 27]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 28]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 12  8  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  8  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 12  1  8]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3 11 13 14]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3 29  2 30  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 31 13 14]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 32  1  4  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 33  5  6 34 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 16  1  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  3 16  1 35 17  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  9

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense ,LSTM,Embedding ,GlobalAveragePooling1D

model=Sequential()
model.add(Embedding(100,10,input_length=20))
model.add(GlobalAveragePooling1D())
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(8,activation='softmax'))

# Embedding layer It is primarily used for learning word embeddings

# 100: This is the first argument, which represents the size of the vocabulary.
#       It indicates that your model will have a vocabulary of 100 unique words or tokens.

# 10: This is the second argument, which represents the dimensionality of the embedding vector
#     for each word in the vocabulary. In this case, each word will be represented as a 10-dimensional vector.

# input_length=20: This is the length of input sequences that will be fed into the Embedding layer.
#                   It indicates that your model expects input sequences of length 20.



In [28]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 10)            1000      
                                                                 
 global_average_pooling1d (  (None, 10)                0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 10)                110       
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 8)                 88        
                                                                 
Total params: 1308 (5.11 KB)
Trainable params: 1308 (5.11 KB)
Non-trainable params: 0 (0.00 Byte)
________________________

In [29]:
history=model.fit(np.array(padded_sequence),training_labels,epochs=400)


Epoch 1/400
2/2 [==============================] - 1s 12ms/step - loss: 2.0783 - accuracy: 0.1176
Epoch 2/400
2/2 [==============================] - 0s 8ms/step - loss: 2.0776 - accuracy: 0.1765
Epoch 3/400
2/2 [==============================] - 0s 8ms/step - loss: 2.0772 - accuracy: 0.2353
Epoch 4/400
2/2 [==============================] - 0s 7ms/step - loss: 2.0770 - accuracy: 0.2647
Epoch 5/400
2/2 [==============================] - 0s 8ms/step - loss: 2.0769 - accuracy: 0.2059
Epoch 6/400
2/2 [==============================] - 0s 8ms/step - loss: 2.0766 - accuracy: 0.2059
Epoch 7/400
2/2 [==============================] - 0s 8ms/step - loss: 2.0762 - accuracy: 0.2059
Epoch 8/400
2/2 [==============================] - 0s 7ms/step - loss: 2.0758 - accuracy: 0.2059
Epoch 9/400
2/2 [==============================] - 0s 8ms/step - loss: 2.0753 - accuracy: 0.2059
Epoch 10/400
2/2 [==============================] - 0s 11ms/step - loss: 2.0748 - accuracy: 0.2059
Epoch 11/400
2/2 [=========

Save Model

In [30]:
inp='hello'
sent=pad_sequences(toknizer.texts_to_sequences([inp]),maxlen=20)
print(sent)
result=np.argmax(model.predict(np.array(sent))) # 0-7
print(result)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 27]]
1/1 [==============================] - 0s 92ms/step
2


In [31]:
#get the label from encoder
f_res=le.inverse_transform(np.array(result).reshape(1))
print(f_res)

['greeting']


## Save Model


In [32]:
import pickle as pk
#save tokinizer
pk.dump(toknizer,open("toknizer.pkl","wb"))

In [33]:
#save encoder
pk.dump(le,open("label_encoder.pkl","wb"))

In [34]:
model.save('model.h5') # save model
from tensorflow.keras.models import load_model
model=load_model('model.h5') # load model

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


Interface

In [35]:
def user_chat():
    while True :
        print("User : ",end="")
        inp=input()

        if inp.lower()=='quit':
            break

        sent=pad_sequences(toknizer.texts_to_sequences([inp]),maxlen=20) #[] len=20

        result=np.argmax(model.predict(np.array(sent),verbose=0)) # 0-7
        # 2 ,3 , 4
        f_res=le.inverse_transform(np.array(result).reshape(1))


        for label in data['data']:

            if label['label']==f_res:

                print('ChatBot : ',np.random.choice(label['responses']))



In [36]:
print("Start Conversation with Chatbot")
user_chat()

Start Conversation with Chatbot
User : hello
ChatBot :  Hi there
User : how are you
ChatBot :  Hi
User : 

KeyboardInterrupt: Interrupted by user

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

# Example text
text_example = "This is a simple example for one-hot encoding."

# Perform one-hot encoding with a vocabulary size of 15
vocab_size = 15
encoded_sequence = one_hot(text_example, vocab_size, filters='')

# Display the results
print(f"Original Text: {text_example}")
print(f"One-Hot Encoded Sequence: {encoded_sequence}")
